# Generated by Django 3.2 on 2021-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queruy',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('statusq', models.IntegerField(default=200)),
                ('timeq', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
