# Generated by Django 3.2 on 2021-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('urlq', models.CharField(max_length=200)),
                ('messageq', models.CharField(max_length=200)),
                ('statusq', models.IntegerField(default=200)),
                ('timeq', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='queruy',
        ),
    ]
