# Generated by Django 3.2 on 2021-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20210527_2141'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['-timeq'], name='status_quer_timeq_2823d7_idx'),
        ),
    ]
