# Generated by Django 3.2 on 2021-05-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_query_status_quer_timeq_2823d7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='uquery',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('urlq', models.CharField(max_length=200)),
                ('startq', models.BooleanField(default=True)),
            ],
        ),
    ]
