# Generated by Django 3.2 on 2021-05-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_uquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uquery',
            name='startq',
            field=models.CharField(max_length=200),
        ),
    ]
